{
    'name': 'MNS REPORT',
    'version': '12.0.1',
    'summary': """MNS REPORT V1""",
    'description': """""",
    'category': 'reporting',
    'author': 'Optesis SA',
    'maintainer': 'Optesis',
    'company': 'Optesis SA',
    'website': 'https://www.optesis.com',
    'depends': ['base','purchase'],
    'data': [
                # 'static/src/css/my_css.xml',
                'views/mns_external_view.xml',
                'views/mns_report_bgfi.xml',
                'views/mns_report_sgbs.xml',
                'views/mns_report_bicis.xml',
              ],
    'images': [''],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
